version: '3.8'

services:
  translator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: antlr_translator
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: ["test"]